forge "https://forge.puppet.com"

mod 'ajxb-faba_icon_theme', git: 'git://github.com/ajxb/puppet-faba_icon_theme.git', ref: '2.0.1'
mod 'ajxb-linuxmint', git: 'git://github.com/ajxb/puppet-linuxmint.git', ref: '1.3.0'
mod 'ajxb-gnome', git: 'git://github.com/ajxb/puppet-gnome.git', ref: 'master'
mod 'ghoneycutt-ssh', '3.56.1'
mod 'puppetlabs-git', '0.5.0'
mod 'puppetlabs-ntp', '6.0.0'
mod 'saz-resolv_conf', '3.1.0'
